### ISSUE TITLE
DCMA Block

### ISSUE THREAD

**Issue by AdityaSoni19031997** [FTUHQ/Machine-Learning-Curriculum#2]
Have you checked my repository before filing a DCMA..
It's just not yours..

I have added many other details which I have found interesting and after that I deleted your fork...

Moreover the whole repository is yours??

I don't think so..

Yours has a readme.md

Mine one has further files and other things..

Kindly Sir please have a look..

(I don't even have a copy of that)

**Comment by maykulkarni** [comment]
Just because you added stuff doesn't mean you discard the original authors
credit. Guess you have no knowledge on how licenses work.

On 01-Dec-2017 9:01 PM, "Aditya Soni" <notifications@github.com> wrote:

Have you checked my repository before filing a DCMA..
It's just not yours..I have added many details which I have found
interesting and after that I deleted your fork...
Kindly have a look again..

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/maykulkarni/Machine-Learning-Curriculum/issues/2>, or mute
the thread

**Comment by AdityaSoni19031997** [comment]
Yep I don't have any knowledge on license (too young for that)because I believe in Open Source contribution..

I will remove them if you insist but for that I will need access again...

**Comment by AdityaSoni19031997** [comment]
In that case I will have a PR sent..
To update the details?

**Comment by AdityaSoni19031997** [comment]
Just wanted to know...
Let's say everyone implemented binary search but does that mean it's their original piece of code/algorithm...
No it's not. No matter how it's implemented..
The idea remains the same...
It's been created by someone else and we all have just been using it...

**Comment by AdityaSoni19031997** [comment]
Care to reply sir?

**Comment by AdityaSoni19031997** [comment]
Regarding the DCMA I think go though the points once again as it says.
The owner should have contacted the user if they find something wrong by creating an issue on their repository..
But you didn't do that...
